=== thorstenhirsch/xmlcraft/docs/screenshots/fixtures/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" type="Book" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Book">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
      <xs:element name="year" type="xs:gYear"/>
      <xs:element name="price" type="Price"/>
      <xs:element name="isbn" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="language" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="de"/>
          <xs:enumeration value="en"/>
          <xs:enumeration value="fr"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="Price">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="currency" type="xs:string" default="EUR"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== thorstenhirsch/xmlcraft/docs/screenshots/fixtures/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="library.xsd" name="City Library">
  <book id="b1" language="en">
    <title>The Lighthouse Keeper's Almanac</title>
    <author>Ada Vance</author>
    <year>2019</year>
    <price currency="EUR">18.50</price>
    <isbn>978-0-00-000000-2</isbn>
  </book>
  <book id="b2" language="de">
    <title>Wege durch den Nebel</title>
    <author>Jonas Weber</author>
    <author>Mira Stein</author>
    <year>2021</year>
    <price>24.00</price>
  </book>
  <book id="b3" language="fr">
    <title>Petit atlas des marées</title>
    <author>Claire Dubois</author>
    <year>2015</year>
    <price currency="EUR">12.90</price>
  </book>
</library>
